---
- name: Deploy Calculator App
  hosts: target
  remote_user: raju
  become: false

  tasks:
    - name: Pull Docker Image from Hub
      # Use your successful DockerHub username here
      community.docker.docker_image:
        name: "kartikeyblaze/calculator"
        tag: latest
        source: pull
      register: docker_pull_result

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Run Container (Automatic Update)
      community.docker.docker_container:
        name: calculator
        image: "kartikeyblaze/calculator:latest"
        state: started
        restart_policy: always
        # Remove /bin/bash unless your Dockerfile specifically requires it
        detach: yes
        recreate: yes  # This replaces the old container if the image changed
